// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgasjwehidcqwdyclrya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnYXNqd2VoaWRjcXdkeWNscnlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MDIwODIsImV4cCI6MjA1NjA3ODA4Mn0.Wv1QwvE-EH40tgbpPPCQatbiWMODyCHYnXmfR4yOebE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);